// <auto-generated />
using System;
using HNGxVideoStreaming.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HNGxVideoStreaming.Migrations
{
    [DbContext(typeof(HNGxVideoStreamingDbContext))]
    [Migration("20231002081804_initial10")]
    partial class initial10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HNGxVideoStreaming.Models.TranscribeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("time");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("time");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UploadKeyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UploadKeyId");

                    b.ToTable("TranscribeDatas");
                });

            modelBuilder.Entity("HNGxVideoStreaming.Models.UploadContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("currentId")
                        .HasColumnType("int");

                    b.Property<bool>("isUploading")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("UploadContexts");
                });

            modelBuilder.Entity("HNGxVideoStreaming.Models.TranscribeData", b =>
                {
                    b.HasOne("HNGxVideoStreaming.Models.UploadContext", "UploadContext")
                        .WithMany("TranscribedData")
                        .HasForeignKey("UploadKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadContext");
                });

            modelBuilder.Entity("HNGxVideoStreaming.Models.UploadContext", b =>
                {
                    b.Navigation("TranscribedData");
                });
#pragma warning restore 612, 618
        }
    }
}
