// <auto-generated />
using HNGxVideoStreaming.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HNGxVideoStreaming.Migrations
{
    [DbContext(typeof(HNGxVideoStreamingDbContext))]
    [Migration("20230930180721_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HNGxVideoStreaming.Models.UploadContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("currentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UploadContexts");
                });
#pragma warning restore 612, 618
        }
    }
}
